name: default

on:
  pull_request:
  push:
    branches: [master]

jobs:
  stylua:
    name: formatting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # CLI arguments
          args: --color always --check lua/
  busted:
    name: tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: dev-comments.nvim
      - uses: actions/checkout@v2
        with:
          repository: nvim-lua/plenary.nvim
          path: plenary.nvim
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly
      - run: nvim --headless --noplugin -u minimal.lua -c "lua require(\"plenary.test_harness\").test_directory_command('test {minimal_init = \"/minimal.lua\"}')"
        working-directory: dev-comments.nvim
        timeout-minutes: 1
