name: docgen

on:
  push:
    branches: [master]

jobs:
  docgen:
    name: generate docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          path: dev-comments.nvim

      - uses: actions/checkout@v2
        with:
          repository: echasnovski/mini.nvim
          path: mini.nvim

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly

      - name: Run docgen
        run: make docgen
        working-directory: dev-comments.nvim

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update doc/dev-comments.txt"
          file_pattern: doc/*.txt
          repository: dev-comments.nvim
          add_options: "-f"
          skip_dirty_check: true
